<a href="https://colab.research.google.com/github/grigorbogikian/Sprint-1/blob/main/ds_112_eda_features_assignment_ag.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Autograded Notebook (Canvas & CodeGrade)

This notebook will be automatically graded. It is designed to test your answers and award points for the correct answers. Following the instructions for each Task carefully.

### Instructions

* **Download this notebook** as you would any other ipynb file
* **Upload** to Google Colab or work locally (if you have that set-up)
* **Delete `raise NotImplementedError()`**
* Write your code in the `# YOUR CODE HERE` space
* **Execute** the Test cells that contain `assert` statements - these help you check your work (others contain hidden tests that will be checked when you submit through Canvas)
* **Save** your notebook when you are finished
* **Download** as a `ipynb` file (if working in Colab)
* **Upload** your complete notebook to Canvas (there will be additional instructions in Slack and/or Canvas)

# Unit 1 Sprint 1 Module 2

## EDA and Features

### Objectives

* Load and csv files
* Use basic Pandas function for data exploration
* Understand the purpose of feature engineering

#### Total notebook points: 13

**Task 1** - Load a dataset via its URL

* Create a Python list named `column_headers` with the following items: `'age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week','native-country', 'income'`.  Lists have the form `listname = ['element 1', 'element 2', element 3']`
* Load the file from the URL provided below using the `column_headers` list you created to name your columns: set the `pd.read_csv()` to `column_headers` using `names =`.  
* Name the DataFrame `adult`

In [ ]:
# Task 1
import pandas as pd
import numpy as np

# URL for the dataset
data_url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'

# YOUR CODE HERE
column_headers = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week','native-country', 'income']
listname = ['element 1', 'element 2', 'element 3']
adult = pd.read_csv(data_url, names = column_headers)

# Print out your DataFrame
adult.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**Task 1 Test**

In [ ]:
# Task 1 - Test

# These tests are for you to check your work before submitting
assert isinstance(column_headers, list), 'Have you created a list of header names?'
assert len(column_headers) == 15, 'Did you include the correct number of items in the column_headers list?'
assert isinstance(adult, pd.DataFrame), 'Have you created a DataFrame named adult?'

# These tests will be completed when you submit your notebook for autograding

**Task 2** - Look at the first and last rows of the DataFrame

* Assign the first **ten (10)** rows of the `adult` DataFrame to `adult_head`
* Assign the last **ten (10)** rows of the `adult` DataFrame to `adult_tail`

In [ ]:
# Task 2

# YOUR CODE HERE

adult_head = adult.head(10)
adult_tail = adult.tail(10)

# Optional: print out adult_head and adult_tail

**Task 2 Test**

In [ ]:
# Task 2 - Test

# These tests are for you to check your work before submitting
assert isinstance(adult_head, pd.DataFrame), 'Have you created a DataFrame named adult_head?'
assert isinstance(adult_tail, pd.DataFrame), 'Have you created a DataFrame named adult_tail?'

# These tests will be completed when you submit your notebook for autograding

**Task 3** - Variable data types

For your `adult` DataFrame, determine the data types for the variables.

* Count the number of `int64` variable types and assign to `number_int64` (your value should be an integer)
* Count the number of `object` variable types and assign to `number_object` (your value should be an integer)

There are different ways to find the data types of the columns in a DataFrame. All you need to do for this task is to count the number of each data type and assign to the corresponding variable.

In [ ]:
# Task 3

# YOUR CODE HERE

adult.dtypes
number_int64 = 6
number_object = 9

**Task 3 Test**

In [ ]:
# Task 3 - Test

# Hidden tests - you will see the results when you submit to Canvas

**Task 4** - DataFrame dimensions

* Find the dimensions of your DataFrame and assign result to the variable `adult_dimension`. Your variable should be a *tuple* and the row dimension should be listed first.

Hint: A tuple looks like this: (1, 2) - a tuple is a collection which is ordered and unchangeable. You can use the function `type(your_variable)` to print the variable type.

Hint 2: The `shape` method returns a tuple - convenient!

In [ ]:
# Task 4

# YOUR CODE


adult_dimension = adult.shape


# Print out the shape
print(adult_dimension)

(32561, 15)

**Task 4 Test**

In [ ]:
# Task 4 - Test

assert isinstance(adult_dimension, tuple), 'Have you created a tuple named adult_dimension?'

# Hidden tests - you will see the results when you submit to Canvas

**Task 5** - Missing values

Are there any missing values in the dataset? Let's check!

* Check for missing values using `.isnull().sum()`
* Count the number of missing values and assign the value to the variable `adult_missing`. Your variable should be an integer.

In [ ]:
# Task 5

# YOUR CODE HERE

adult.isnull().sum()
adult_missing = 0

**Task 5 Test**

In [ ]:
# Task 5 - Test

# Hidden tests - you will see the results when you submit to Canvas

**Task 6** - Viewing DataFrame statistics

Let's look at some of the *summary statistics* of our dataset. We can use the .describe() function in order to see the summary statistics of the numeric columns.

Look at the statistics for the `adult` DataFrame and then complete the following two tasks:

* Find the value for the mean `age` and assign it to the variable `mean_age` (your value should be a float and defined to two decimal places)
* Find the standard deviation (std) for the `hours-per-week` variable and assign it to `std_hpw` (your value should be a float and defined to two decimal places)

Are there any values shown that might be a code for missing data?  We'll learn how to change the values in a DataFrame in the next module.

In [ ]:
# Task 6

# YOUR CODE HERE

adult.describe()
mean_age = 38.58
std_hpw = 13.64

**Task 6 Test**

In [ ]:
# Task 6 - Test

# Hidden tests - you will see the results when you submit to Canvas

**Task 7** - Summary statistics for non-numeric columns

We have some columns in this dataset that are non-numeric or object columns. This is usually a string object. Let's use the `describe()` function again but include the argument `exclude='number'` to exclude the numeric columns.

Using the results of `describe(exclude='number')`, complete the following two tasks:

* Find the number of unique `education` values and assign it to `unique_edu` (your value should be an integer)
* Find the number of times the most frequent observation for `income` occurs and assign it to `freq_income` (your value should be an integer) *(Note: this is not the income value itself, just how many times it occurs)*

In [ ]:
# Task 7

# YOUR CODE HERE

adult.describe(exclude='number')
unique_edu = 16
freq_income = 24720

In [ ]:
adult.describe(exclude='number')

,workclass,education,marital-status,occupation,relationship,race,sex,native-country,income
count,32561,32561,32561,32561,32561,32561,32561,32561,32561
unique,9,16,7,15,6,5,2,42,2
top,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,<=50K
freq,22696,10501,14976,4140,13193,27816,21790,29170,24720

**Task 7 Test**

In [ ]:
# Task 7 - Test

# Hidden tests - you will see the results when you submit to Canvas

**Task 8** - Finding value counts

Let's look more specifically at the `relationship` column and perform a count of the number of observations for each category. We can see how many categories we have by using the `.unique()` method on the column. Then, we can use `.value_counts()` to count the number of observations in each category.

* View the unique values in the `relationship` column with `.unique()`
* View the number of observations for each value with `.value_counts()`
* Find the counts for `Other-relative` and assign to the variable `adult_other_rel`

In [ ]:
# Task 8

# YOUR CODE HERE

adult['relationship'].unique()
adult['relationship'].value_counts()
adult_other_rel = 981

**Task 8 Test**

In [ ]:
# Task 8 - Test

# Hidden tests - you will see the results when you submit to Canvas

**Task 9** - Create a Series

A column of a DataFrame is a pandas Series. Using the `adult` DataFrame, create a Series from the `occupation` column.

* Create a Series from the `occupation` column and name it `adult_occup`

In [ ]:
#adult.head()
adult['occupation']

0              Adm-clerical
1           Exec-managerial
2         Handlers-cleaners
3         Handlers-cleaners
4            Prof-specialty
                ...
32556          Tech-support
32557     Machine-op-inspct
32558          Adm-clerical
32559          Adm-clerical
32560       Exec-managerial
Name: occupation, Length: 32561, dtype: object

In [ ]:
# Task 9

# YOUR CODE HERE


adult_occup = adult['occupation']
print(adult_occup)

0              Adm-clerical
1           Exec-managerial
2         Handlers-cleaners
3         Handlers-cleaners
4            Prof-specialty
                ...
32556          Tech-support
32557     Machine-op-inspct
32558          Adm-clerical
32559          Adm-clerical
32560       Exec-managerial
Name: occupation, Length: 32561, dtype: object

**Task 9 Test**

In [ ]:
# Task 9 - Test

# These tests are for you to check your work before submitting
assert isinstance(adult_occup, pd.Series), 'Have you created the correct Series?'

# Hidden tests - you will see the results when you submit to Canvas

## Feature Creation

Next you will focus on learning how to create new features from exisiting data. There are many ways to create features in your datasets; we'll only focus on a few here. Let's get started!

**Task 10** - Load the data set

* Using the provided URL, load the Ames Housing Data into a DataFrame called `house`
* View your DataFrame

In [ ]:
# Task 10

# Imports
import pandas as pd

# Dataset URL

data_url = 'https://raw.githubusercontent.com/LambdaSchool/data-science-practice-datasets/main/unit_1/Housing/Ames%20Iowa%20Housing%20Data.csv'

# YOUR CODE HERE

house = pd.read_csv(data_url)

# View your DataFrame
house.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

**Task 10 Test**

In [ ]:
# Task 10 - Test

# These tests are for you to check your work before submitting
assert isinstance(house, pd.DataFrame), 'Have you created a DataFrame named house?'

# Hidden tests - you'll see results when you submit to Canvas

**Task 11** - Create a new feature

Now that we have the data loaded, we're going to create a new feature. We can use the some of the existing features, in this case, the total number of bathrooms in one column.

* Create a new variable called `Total_Bathrooms` that contains the total number of full and half bathrooms in the house.  

*Hint: Identify all the columns with bath in the title and add their values together. There are four columns to add together.  Add one to the total for each full or half bathroom.*

In [ ]:
# Task 11

# YOUR CODE HERE

house['Total_Bathrooms'] = house['FullBath'] + house['HalfBath'] + house['BsmtFullBath'] + house['BsmtHalfBath'] + 1
house['Total_Bathrooms'].head()

0    5
1    4
2    5
3    3
4    5
Name: Total_Bathrooms, dtype: int64

**Task 11 Test**

In [ ]:
# Task 11 - Test

assert 'Total_Bathrooms' in house.columns, 'Did you add the new column?'

# Hidden tests - you'll see results when you submit to Canvas

# View all the bathroom columns
house[['Total_Bathrooms','BsmtFullBath','BsmtHalfBath','FullBath','HalfBath']].head()

   Total_Bathrooms  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath
0                5             1             0         2         1
1                4             0             1         2         0
2                5             1             0         2         1
3                3             1             0         1         0
4                5             1             0         2         1

**Task 12** - Create a new feature column

Next we're going to create another new column by "encoding" an existing column. Using the `LotArea` column, we'll assign values according the the area of the lot.

* Create a new column called `Large_Lot` that takes on the following values:
    * 0 when `LotArea` is **less** than 10,000
    * 1 when `LotArea` is **greater than or equal** to 10,000

In [ ]:
# Task 12

# YOUR CODE HERE

house['Large_Lot'] = (house['LotArea'] >= 10000).astype(int)

# View the new column
house[['LotArea', 'Large_Lot']].head()

   LotArea  Large_Lot
0     8450          0
1     9600          0
2    11250          1
3     9550          0
4    14260          1

**Task 12 Test**

In [ ]:
# Task 12 - Test

assert 'Large_Lot' in house.columns, 'Did you add the Large_Lot column?'

# Hidden tests - you'll see results when you submit to Canvas

**Task 13** - Create another feature

Let's continue with creating new features. This time, we'll focus on encoding for the sale month.

* Create a new column called `Summer_Sale` that takes on the following values:
    * 0 if the sale month was in September - May (`MoSold` = 1-5, 9-12)
    * 1 if the sale month was in June, July or August (`MoSold` = 6, 7 or 8)

In [ ]:
# Task 13

# YOUR CODE HERE

house['Summer_Sale'] = (house['MoSold'] >= 6).astype(int)

# View the new column
house[['MoSold', 'Summer_Sale']]

      MoSold  Summer_Sale
0          2            0
1          5            0
2          9            1
3          2            0
4         12            1
...      ...          ...
1455       8            1
1456       2            0
1457       5            0
1458       4            0
1459       6            1

[1460 rows x 2 columns]

**Task 13 Test**

In [ ]:
# Task 13 - Test

assert 'Summer_Sale' in house.columns, 'Did you add the Summer_Sale column?'

# Hidden tests - you'll see results when you submit to Canvas